name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    uses: Spread-Studio-Apps/actions/.github/workflows/build.yml@main
    with:
      image_name: ${{ github.repository }}
    secrets: inherit
    permissions:
      contents: read
      packages: write
  release-notification:
    uses: Spread-Studio-Apps/actions/.github/workflows/patch-platform.yml@main
    needs: docker
    secrets: inherit
