name: Patch App Version in Platform

on:
  #push:
  #  tags:
  #    - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to apply to the app.'
        required: true

jobs:
  release-notification:
    uses: Spread-Studio-Apps/actions/.github/workflows/patch-platform.yml@main
    secrets: inherit
